### ISSUE TITLE
Internal Error 500 is occurred with QUICK export.

### ISSUE THREAD

**Issue by two-pack** [two-pack/redmine_xls_export#16]
### What steps will reproduce the problem?

Internal Error 500 is occurred with QUICK export.
### What is the expected output? What do you see instead?

Zip file with a issue list is exported.
### What version of the product are you using? On what operating system?
- version
  0.2.1.t1
- OS
  Windows 7
- Redmine
  BitNami Redmine Stack Redmine 2.2.2-0
### Please provide any additional information below.
- Official plugin is not occurred.
- The environment is added a project and a issue only with admin account.

**Comment by two-pack** [comment]
The log on production is following.

```
Started GET "/redmine/projects/test/issues_xls_export_current" for 127.0.0.1 at 2013-02-09 08:04:42 +0900
Processing by XlsExportController#export_current as HTML
  Parameters: {"project_id"=>"test"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 83ms

TypeError (can't dup NilClass):
  spreadsheet (0.7.9) lib/spreadsheet/encodings.rb:17:in `dup'
  spreadsheet (0.7.9) lib/spreadsheet/encodings.rb:17:in `internal'
  spreadsheet (0.7.9) lib/spreadsheet/excel/writer/biff8.rb:43:in `_unicode_string'
  spreadsheet (0.7.9) lib/spreadsheet/excel/writer/biff8.rb:36:in `unicode_string'
  spreadsheet (0.7.9) lib/spreadsheet/excel/writer/workbook.rb:385:in `block in write_formats'
  spreadsheet (0.7.9) lib/spreadsheet/excel/writer/workbook.rb:380:in `each'
  spreadsheet (0.7.9) lib/spreadsheet/excel/writer/workbook.rb:380:in `write_formats'
  spreadsheet (0.7.9) lib/spreadsheet/excel/writer/workbook.rb:431:in `write_from_scratch'
  spreadsheet (0.7.9) lib/spreadsheet/excel/writer/workbook.rb:644:in `write_workbook'
  spreadsheet (0.7.9) lib/spreadsheet/writer.rb:12:in `write'
  spreadsheet (0.7.9) lib/spreadsheet/workbook.rb:124:in `write'
  plugins/redmine_xls_export/lib/xls_export.rb:265:in `issues_to_xls2'
  plugins/redmine_xls_export/app/controllers/xls_export_controller.rb:116:in `export_to_string'
  plugins/redmine_xls_export/app/controllers/xls_export_controller.rb:50:in `export_current'
  actionpack (3.2.11) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.11) lib/active_support/callbacks.rb:469:in `_run__222470956__process_action__540223765__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.11) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.11) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.11) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.11) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.11) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.11) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.11) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:601:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.11) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `_run__194482560__call__839920204__callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.11) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.11) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.11) lib/action_dispatch/middleware/static.rb:62:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.11) lib/rails/engine.rb:479:in `call'
  railties (3.2.11) lib/rails/application.rb:223:in `call'
  railties (3.2.11) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.1) lib/rack/urlmap.rb:64:in `block in call'
  rack (1.4.1) lib/rack/urlmap.rb:49:in `each'
  rack (1.4.1) lib/rack/urlmap.rb:49:in `call'
  thin (1.3.1) lib/thin/connection.rb:80:in `block in pre_process'
  thin (1.3.1) lib/thin/connection.rb:78:in `catch'
  thin (1.3.1) lib/thin/connection.rb:78:in `pre_process'
  thin (1.3.1) lib/thin/connection.rb:53:in `process'
  thin (1.3.1) lib/thin/connection.rb:38:in `receive_data'
  eventmachine-1.0.0-x86 (mingw32) lib/eventmachine.rb:187:in `run_machine'
  eventmachine-1.0.0-x86 (mingw32) lib/eventmachine.rb:187:in `run'
  thin (1.3.1) lib/thin/backends/base.rb:61:in `start'
  thin (1.3.1) lib/thin/server.rb:159:in `start'
  thin (1.3.1) lib/thin/controllers/controller.rb:86:in `start'
  thin (1.3.1) lib/thin/runner.rb:185:in `run_command'
  thin (1.3.1) lib/thin/runner.rb:151:in `run!'
  thin (1.3.1) bin/thin:6:in `<top (required)>'
  bin/thin:16:in `load'
  bin/thin:16:in `<main>'
```

**Comment by two-pack** [comment]
This issue re-procedures on Mac OS X 10.7.5 with Redmine 2.1.4 .

> TypeError (can't dup NilClass):

Maybe this error is caused by no initializing date format settings.
When I show _Administration > Plugins > Configure_ above environment, date format settings are empty.

NOTE: Development environment DIDN'T occur the issue, but Production environment occurred it.

**Comment by two-pack** [comment]
> NOTE: Development environment DIDN'T occur the issue, but Production environment occurred it.
> It's my mistake. This issue occurred on development environment with same DB.
